version: 5.1.0
variant: default
logo:
    text: Hanz
navbar:
    menu:
        Home: /
        çŸ¥è¯†åº“: /wiki/
        ç‰©ç†: /wiki/physics/
        è®¡ç®—æœº: /wiki/cs/
        æ•™å­¦: /teaching
        è®¡åˆ’: /plan
        è´­ç‰©: /shopping
        å…³äº: /about
article:
    toc: true
    readtime: true
    update_time: auto
footer:
    copyright: ç”¨ğŸ’–å‘ç”µ
math:
  enable: true
  engine: mathjax