version: 5.1.0
variant: default
logo:
    text: æˆ‘çš„çŸ¥è¯†åº“
navbar:
    menu:
        Home: /
        çŸ¥è¯†åº“: /wiki/
        ç‰©ç†: /wiki/physics/
        è®¡ç®—æœº: /wiki/cs/
        å…³äº: /about
article:
    toc: true
    readtime: true
    update_time: auto
footer:
    copyright: ç”¨ğŸ’–å‘ç”µ
